
[server]
port = 5000
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[meta]
title = "SismaVer2 - Monitoraggio Sismico e Vulcanico in Italia"
description = "Sistema nazionale di monitoraggio sismico, vulcanico e meteorologico. Informazioni in tempo reale su terremoti, vulcani e meteo in Italia."
author = "SismaVer2"
keywords = "terremoti italia, monitoraggio sismico, vulcani italia, protezione civile, meteo italia, emergenza sismica"
